export const INSERT_FORM_REQUEST = 'INSERT_FORM_REQUEST';
export const INSERT_FORM_SUCCESS = 'INSERT_FORM_SUCCESS';
export const INSERT_FORM_FAILURE = 'INSERT_FORM_FAILURE';

export const GET_KONTRASEPSI_REQUEST = 'GET_KONTRASEPSI_REQUEST';
export const GET_KONTRASEPSI_SUCCESS = 'GET_KONTRASEPSI_SUCCESS';
export const GET_KONTRASEPSI_FAILURE = 'GET_KONTRASEPSI_FAILURE';

export const GET_PROPINSI_REQUEST = 'GET_PROPINSI_REQUEST';
export const GET_PROPINSI_SUCCESS = 'GET_PROPINSI_SUCCESS';
export const GET_PROPINSI_FAILURE = 'GET_PROPINSI_FAILURE';

export const GET_REKAPITULASI_PROPINSI_REQUEST = 'GET_REKAPITULASI_PROPINSI_REQUEST';
export const GET_REKAPITULASI_PROPINSI_SUCCESS = 'GET_REKAPITULASI_PROPINSI_SUCCESS';
export const GET_REKAPITULASI_PROPINSI_FAILURE = 'GET_REKAPITULASI_PROPINSI_FAILURE';
